name: doctor_portal_cms
description: Life HIS application for CMS Hospital

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  catcher: ^0.3.2
  connectivity: ^0.4.8+2
  date_picker_timeline: ^1.2.1
  date_time_picker: ^2.0.0
  dio: ^3.0.9
  file_picker: ^2.1.7
  flutter_html: ^0.11.1
  flutter_icons: ^1.1.0
  flutter_pdfview: ^1.1.0
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_spinkit: ^5.0.0
  flutter_summernote: ^0.2.2
  flutter_typeahead: ^2.0.0
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^9.0.0
  html: ^0.14.0+4
  intl: ^0.17.0
  json_annotation: ^3.0.0
  moor: ^1.6.1
  moor_flutter: ^1.6.0
  mysql1: ^0.17.1
  navigationbar_bro: ^0.0.3
  permission_handler: ^5.0.0+hotfix.6
  pinput: ^0.2.6
  provider: ^4.1.2
  shared_preferences: ^0.5.6+3
  shimmer: ^1.1.2
  smooth_star_rating: ^1.1.1
  trust_fall: ^1.0.4
  webview_flutter: ^1.0.7
  notus: ^0.1.5
  url_launcher: ^5.0.0
  quill_delta: ^1.0.0
  notustohtml: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.2.0
  moor_generator: ^1.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/cms_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locale/localization_en.json
    - assets/locale/localization_es.json
    - assets/images/
    - assets/images/logo/chazikkat_logo.png
    - assets/images/splash/cesa_splash_bg.jpg
    - assets/images/local_image/dummy.jpg
    - assets/images/local_image/cms_logo.png
    - assets/images/local_image/female.jpg
    - assets/images/local_image/male.jpg
    - assets/images/local_image/red.png
    - assets/images/local_image/green.png
    - assets/images/local_image/inpatient.png
    - assets/images/local_image/outpatient.png
    - assets/images/local_image/free_bed.png
    - assets/icons/allergy_icon.png
    - assets/icons/consultation_icon.png
    - assets/icons/labresults_icon.png
    - assets/icons/referral_icon.png
    - assets/icons/vitals_icon.png
    - assets/icons/upload_icon.png
    - assets/images/loading/loading.gif
    - assets/app_icon/mosc_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
